version: '3'
services:
  webserver:
    image: puckel/docker-airflow
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: s3,gcp_api
    restart: always
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432

